### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by ahamid** [nathansobo/monarch#8]
Hello, I'm curious about the status of Monarch, and which is the real Monarch between @nathansobo and @maxbrunsfeld.  Specifically I'm interested in experimenting with it in the client but can't tell if that is possible at this point, whether it requires browserify+coffeescript transform, etc.

**Comment by maxbrunsfeld** [comment]
I would say that this repo is the real one. The difference is that http://github.com/maxbrunsfeld/monarch contains an experimental server-side implementation of monarch as well. You can concatenate all of the source code into a single javascript file suitable for inclusion in an html page by running `cake build` from the root of the directory. `cake` is a CLI tool that comes with coffee-script; see the [Cakefile](https://github.com/nathansobo/monarch/blob/master/Cakefile).

Regarding the status, I'll let @nathansobo comment on that, but I wouldn't say that either of us is actively using or maintaining monarch.

**Comment by nathansobo** [comment]
Yeah, I would call it an unmaintained exposition of some cool ideas. If you use it, plan on forking. Wish I had the time to say otherwise.

**Comment by ahamid** [comment]
Thanks for the response guys.
